/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Uber;
import Business.UberDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;
/**
 *
 * @author rohan
 */
public class ViewCarJPanel extends javax.swing.JPanel {
        private JPanel bottomPanel;
        private Uber uber;
        private UberDirectory uberDirectory;
      public String s;
    /**
     * Creates new form ViewCarJPanel
     */
    

    ViewCarJPanel(JPanel bottomPanel, Uber uber) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.uber = uber;
        populateCarDetails();
        
    }
    
    private void  populateCarDetails(){
        carNameTextField.setText(uber.getCarName());
        carBrandTextField.setText(uber.getCarBrand());
        carCityTextField.setText(uber.getCarAvailableCity());
        carManufYearTextField.setText(String.valueOf(uber.getCarManufacYear()));
        carManufacturerTextField.setText(uber.getCarManufacturer());
        carMaxSeatsTextField.setText(String.valueOf(uber.getCarMaxSeats()));
        carMinSeatsTextField.setText(String.valueOf(uber.getCarMinSeats()));
        carModelNumberTextField.setText(uber.getCarModelNum());
        carSerialNumberTextField.setText(String.valueOf(uber.getCarSerialNum()));
        if(uber.isCarAvailability() == true){
            radioYes.setSelected(true);
            radioYes.setEnabled(false);
            radioNo.setEnabled(false);
        }
        else{
            
            radioNo.setSelected(true);
            radioYes.setEnabled(false);
            radioNo.setEnabled(false);
        }
        if(uber.isCarMaintenanceCertificate() == true){
            radioTrue.setSelected(true);
            radioTrue.setEnabled(false);
            radioFalse.setEnabled(false);
        }
        else{
            
            radioFalse.setSelected(true);
            radioTrue.setEnabled(false);
            radioFalse.setEnabled(false);
        }
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        carNameTextField = new javax.swing.JTextField();
        carBrandTextField = new javax.swing.JTextField();
        carManufYearTextField = new javax.swing.JTextField();
        carMinSeatsTextField = new javax.swing.JTextField();
        carMaxSeatsTextField = new javax.swing.JTextField();
        carSerialNumberTextField = new javax.swing.JTextField();
        carModelNumberTextField = new javax.swing.JTextField();
        carCityTextField = new javax.swing.JTextField();
        carManufacturerTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        modifyTextField = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        radioYes = new javax.swing.JCheckBox();
        radioNo = new javax.swing.JCheckBox();
        radioTrue = new javax.swing.JCheckBox();
        radioFalse = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 239, 243));

        jLabel2.setText("Car Name  :");

        jLabel3.setText("Certificate Available?  :");

        jLabel4.setText("Brand  :");

        jLabel5.setText("Availability  :");

        jLabel6.setText("City Available in  :");

        jLabel7.setText("Manufacturer  :");

        jLabel8.setText("Manufacture Year  :");

        jLabel9.setText("Minumum seats  :");

        jLabel10.setText("Maximum Seats  :");

        jLabel11.setText("Serial Number  :");

        jLabel12.setText("Model Number  :");

        carNameTextField.setEditable(false);
        carNameTextField.setEnabled(false);

        carBrandTextField.setEditable(false);
        carBrandTextField.setEnabled(false);

        carManufYearTextField.setEditable(false);
        carManufYearTextField.setEnabled(false);

        carMinSeatsTextField.setEditable(false);
        carMinSeatsTextField.setEnabled(false);

        carMaxSeatsTextField.setEditable(false);
        carMaxSeatsTextField.setEnabled(false);

        carSerialNumberTextField.setEditable(false);
        carSerialNumberTextField.setEnabled(false);

        carModelNumberTextField.setEditable(false);
        carModelNumberTextField.setEnabled(false);

        carCityTextField.setEditable(false);
        carCityTextField.setEnabled(false);

        carManufacturerTextField.setEditable(false);
        carManufacturerTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jLabel1.setText("View Car Details ");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        modifyTextField.setBackground(new java.awt.Color(255, 255, 255));
        modifyTextField.setForeground(new java.awt.Color(255, 51, 51));
        modifyTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Catalog last updated on:");

        buttonGroup1.add(radioYes);
        radioYes.setText("Yes");
        radioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioNo);
        radioNo.setText("No");

        buttonGroup2.add(radioTrue);
        radioTrue.setText("Yes");

        buttonGroup2.add(radioFalse);
        radioFalse.setText("No");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(carManufacturerTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carCityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carModelNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carSerialNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carMaxSeatsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carMinSeatsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carManufYearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carBrandTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radioTrue)
                            .addGap(18, 18, 18)
                            .addComponent(radioFalse))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radioYes)
                            .addGap(18, 18, 18)
                            .addComponent(radioNo))))
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(247, 247, 247))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modifyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                    .addComponent(jLabel2)
                                                                                    .addComponent(carNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel4))
                                                                            .addComponent(carBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel8))
                                                                    .addComponent(carManufYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel9))
                                                            .addComponent(carMinSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10))
                                                    .addComponent(carMaxSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addComponent(carSerialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))
                                    .addComponent(carModelNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(carCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carManufacturerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(modifyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioYes)
                            .addComponent(radioNo))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioTrue)
                            .addComponent(radioFalse))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        carNameTextField.setEditable(true);
        carBrandTextField.setEditable(true);
        carManufYearTextField.setEditable(true);
        carMinSeatsTextField.setEditable(true);
        carMaxSeatsTextField.setEditable(true);
        carSerialNumberTextField.setEditable(true);
        carModelNumberTextField.setEditable(true);
        carCityTextField.setEditable(true);
        carModelNumberTextField.setEditable(true);
        carManufacturerTextField.setEditable(true);
        carNameTextField.setEnabled(true);
        carBrandTextField.setEnabled(true);
        carManufYearTextField.setEnabled(true);
        carMinSeatsTextField.setEnabled(true);
        carMaxSeatsTextField.setEnabled(true);
        carSerialNumberTextField.setEnabled(true);
        carModelNumberTextField.setEnabled(true);
        carCityTextField.setEnabled(true);
        carModelNumberTextField.setEnabled(true);
        carManufacturerTextField.setEnabled(true);
        radioFalse.setEnabled(true);
        radioTrue.setEnabled(true);
        radioYes.setEnabled(true);
        radioNo.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String name = carNameTextField.getText();  
        if(name == null || name.equals("")){
        JOptionPane.showMessageDialog(null, "Name can't be empty");
        return;
        }
        
        String brand = carBrandTextField.getText();
        if(brand == null || brand.equals("")){
        JOptionPane.showMessageDialog(null, "Brand can't be empty");
        return;
        }
        
        String year = (carManufYearTextField.getText());
        if(year == null || year.equals("")){
        JOptionPane.showMessageDialog(null, "Year can't be empty");
        return;
        }
        
        String minSeats = (carMinSeatsTextField.getText());
        if(minSeats == null || minSeats.equals("")){
        JOptionPane.showMessageDialog(null, "Seats can't be empty");
        return;
        }
        
        String maxSeats = (carMinSeatsTextField.getText());
        if(maxSeats == null || maxSeats.equals("")){
        JOptionPane.showMessageDialog(null, "Seats can't be empty");
        return;
        }
        
        String serialNumber = (carSerialNumberTextField.getText());
        if(serialNumber == null || serialNumber.equals("")){
        JOptionPane.showMessageDialog(null, "Serial Number can't be empty");
        return;
        }
        
        String modelNumber = carModelNumberTextField.getText();
        if(modelNumber == null || modelNumber.equals("")){
        JOptionPane.showMessageDialog(null, "Model Number can't be empty");
        return;
        }
        
        String city = carCityTextField.getText();
        if(city == null || city.equals("")){
        JOptionPane.showMessageDialog(null, "City can't be empty");
        return;
        }
        
        String manufacturer = carManufacturerTextField.getText();
        if(manufacturer == null || manufacturer.equals("")){
        JOptionPane.showMessageDialog(null, "Car Manufacturer can't be empty");
        return;
        }
        
        try{
               Integer.parseInt(carManufYearTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Year");
            }
        
        try{
               Integer.parseInt(carMinSeatsTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Min seats");
            }
        
        try{
               Integer.parseInt(carMaxSeatsTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Max seats");
            }
        
        try{
               Integer.parseInt(carSerialNumberTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Serial Number");
            }
        
        
        
         
        
        
        
        uber.setCarName(carNameTextField.getText());
        uber.setCarBrand(carBrandTextField.getText());
        uber.setCarManufacYear(Integer.parseInt(carManufYearTextField.getText()));
        uber.setCarMinSeats(Integer.parseInt(carMinSeatsTextField.getText()));
        uber.setCarMaxSeats(Integer.parseInt(carMaxSeatsTextField.getText()));
        uber.setCarSerialNum(Integer.parseInt(carSerialNumberTextField.getText()));
        uber.setCarModelNum(carModelNumberTextField.getText());
        uber.setCarAvailableCity(carCityTextField.getText());
        uber.setCarManufacturer(carManufacturerTextField.getText());
        if(radioYes.isSelected()){
            uber.setCarAvailability(true);
        }
        else{
            uber.setCarAvailability(false);
            
        }
        
        if(radioTrue.isSelected()){
            uber.setCarMaintenanceCertificate(true);
        }
        else{
            uber.setCarMaintenanceCertificate(false);
            
        }
        
        
        
        JOptionPane.showMessageDialog(null, "Car Details updated successfully"); 
        carNameTextField.setEditable(false);
        carBrandTextField.setEditable(false);
        carManufYearTextField.setEditable(false);
        carMinSeatsTextField.setEditable(false);
        carMaxSeatsTextField.setEditable(false);
        carSerialNumberTextField.setEditable(false);
        carModelNumberTextField.setEditable(false);
        carCityTextField.setEditable(false);
        carManufacturerTextField.setEditable(false);
        radioTrue.setEnabled(false);
        radioFalse.setEnabled(false);
        radioYes.setEnabled(false);
        radioNo.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
            Date d = new Date();
       
        modifyTextField.setText(sdf.format(d));
         s = sdf.format(d);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        bottomPanel.remove(this);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        Component [] comps = this.bottomPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageCarJPanel){
                ManageCarJPanel managePanel = (ManageCarJPanel) comp;
                managePanel.populateTable(uberDirectory,"ff");
            }
        }
        layout.previous(bottomPanel);
    }//GEN-LAST:event_btnBackActionPerformed
/**/
    
    /**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField carBrandTextField;
    private javax.swing.JTextField carCityTextField;
    private javax.swing.JTextField carManufYearTextField;
    private javax.swing.JTextField carManufacturerTextField;
    private javax.swing.JTextField carMaxSeatsTextField;
    private javax.swing.JTextField carMinSeatsTextField;
    private javax.swing.JTextField carModelNumberTextField;
    private javax.swing.JTextField carNameTextField;
    private javax.swing.JTextField carSerialNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel modifyTextField;
    private javax.swing.JCheckBox radioFalse;
    private javax.swing.JCheckBox radioNo;
    private javax.swing.JCheckBox radioTrue;
    private javax.swing.JCheckBox radioYes;
    // End of variables declaration//GEN-END:variables

    
}
